# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hedge Beta' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hedge Beta

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Invites'
pod 'Firebase/Messaging'
pod 'GoogleSignIn'
pod 'Crashlytics'
pod 'Fabric'
pod 'SCLAlertView'
pod 'NVActivityIndicatorView'
pod 'paper-onboarding'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire'
pod 'Charts', '3.1.0'
pod 'InstantSearch-iOS'
pod 'InstantSearch-Core-Swift'
pod 'AlgoliaSearch-Client-Swift'
pod 'SendBirdSDK'
pod 'IQKeyboardManagerSwift', '5.0.8'
pod 'AlamofireImage'
pod 'UIDropDown'
pod 'MessageKit'
pod 'BBBadgeBarButtonItem'
pod 'AZDropdownMenu'
pod 'MIBadgeButton-Swift', :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'


end
