# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipMe' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipMe

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'IQKeyboardManagerSwift'
  pod 'AMWaveTransition'
  pod 'DGElasticPullToRefresh'
  pod 'GTProgressBar'
  pod 'GradientProgressBar', '~> 1.0'
  pod 'FoldingCell', '~> 2.0.3' 
  pod 'SCLAlertView'
  pod 'NVActivityIndicatorView'
end
